### ISSUE TITLE
Пасхалка не работает

### ISSUE THREAD

**Issue by SNR93** [vuit-qa/qlyuker#2]
Добрый день. Пасхалка не работает. А что она должна делать?
Получаю ошибку 403 при обращении к API и 
SyntaxError: Unexpected token 'Н', "Неверные данные" is not valid JSON

Да и, такое ощущение, что скрипт автотыка не работает... Ошибок нет, но и крутки нет

**Comment by Sovenok-Hacker** [comment]
Кликает раз в 30 сек

**Comment by vuit-qa** [comment]
Возможно фиксанули)
По идее она в - баланс загоняет. На то она и пасхалка. Автоматизатор работает

**Comment by SNR93** [comment]
Кликает раз в 30 секунд....? Я думал скрипт посылает раз в 30 секунд инфу о том, что он кликнул 5000 раз

**Comment by Sovenok-Hacker** [comment]
Спасибо автору, сейчас пишу headless-бота на Клюкер на Bun-скрипте
![image](https://github.com/user-attachments/assets/42a77f22-68c1-4f9d-8c7c-1175e1b96cf3)

**Comment by Sovenok-Hacker** [comment]
https://gitverse.ru/Sovenok-Hacker/qlyuker-bot

**Comment by nikitagears** [comment]
> https://gitverse.ru/Sovenok-Hacker/qlyuker-bot

Приветствую. Дёрнул INIT_DATA, прописал в переменные, проверил что внутрь скрипта она попадает, но скрипт отбивает 403 респонс при аутентификации. Как быть?

**Comment by Sovenok-Hacker** [comment]
IP русский? Пробовал VPS, не работает, только cloud.ru Москва работает

**Comment by nikitagears** [comment]
> IP русский? Пробовал VPS, не работает, только cloud.ru Москва работает

Шведская впска, скрипт браузерный из этого репа работает на ней. А через твой скрипт почему то не даёт авторизоваться, к сожалению. Куда ещё капнуть?

**Comment by Sovenok-Hacker** [comment]
> > IP русский? Пробовал VPS, не работает, только cloud.ru Москва работает
> 
> Шведская впска, скрипт браузерный из этого репа работает на ней. А через твой скрипт почему то не даёт авторизоваться, к сожалению. Куда ещё капнуть?

Да, печально, та же беда, очень странно. Можно прокси попробовать.

**Comment by Sovenok-Hacker** [comment]
> > https://gitverse.ru/Sovenok-Hacker/qlyuker-bot
> 
> Приветствую. Дёрнул INIT_DATA, прописал в переменные, проверил что внутрь скрипта она попадает, но скрипт отбивает 403 респонс при аутентификации. Как быть?

А как ставил параметры? Есть проблемы с энвом в Bun, работает нормально только через `export INIT_DATA=...`

**Comment by nikitagears** [comment]
> > > https://gitverse.ru/Sovenok-Hacker/qlyuker-bot
> > 
> > 
> > Приветствую. Дёрнул INIT_DATA, прописал в переменные, проверил что внутрь скрипта она попадает, но скрипт отбивает 403 респонс при аутентификации. Как быть?
> 
> А как ставил параметры? Есть проблемы с энвом в Bun, работает нормально только через `export INIT_DATA=...`

Прописывал и в .env,, process.env, экспорт, ещё для верочки в баш профайл. В скрипте перед аутентификацией вывожу в консоль содержимое init_data, содержимое корректное

**Comment by Sovenok-Hacker** [comment]
Переименовал, https://gitverse.ru/Sovenok-Hacker/klyuker-bot
